name: odootel
services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
  zipkin:
    image: ghcr.io/openzipkin/zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - 9411:9411
    depends_on:
      prometheus:
        condition: service_started
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U odoo" ]
      interval: 1s
      timeout: 30s
      retries: 30
    depends_on:
      zipkin:
        condition: service_started
  odoo:
    build:
      dockerfile: Dockerfile
    environment:
      - OTEL_SERVICE_NAME=odoo
      - OTEL_TRACES_EXPORTER=zipkin
      - OTEL_METRICS_EXPORTER=prometheus
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - OTEL_EXPORTER_PROMETHEUS_ENDPOINT=http://prometheus:9090
    ports:
      - 8069:8069
    command: ["--database", "odoo", "-i", "base"]
    depends_on:
      db:
        condition: service_healthy